### ISSUE TITLE
För öppet

### ISSUE THREAD

**Issue by arvestad** [brainstorm/biobits#2]
Hej Roman,
Jag vill be dig plocka ner detta repo. En ärlig student har rapporterat att det kommer upp när man börjar googla på detaljer i lab4... 

Tack på förhand,
L

**Comment by brainstorm** [comment]
Oops, förlåt, jag fick ingen notis av den här ärende... kommer att stänga det alldeles strax! :+1:

**Comment by arvestad** [comment]
Tack!
